config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get "home/about" => "homes#about"

  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end


resources :users, only: [:index, :show, :edit, :update]

delete '/books' => 'books#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
	validates :body, presence: true,
	                 length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: {in: 2..20}
  validates :introduction,length: { maximum: 50}

  attachment :profile_image
  def email_required?
   false
  end
  def email_changed?
   false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
	      root_path
  end


  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit,:update,:destroy]}
     #制限

	def create
    @user = current_user
		@book = Book.new(book_params)
    @book.user_id = (current_user.id)
     if @book.save
      flash[:notice] = "You have creatad book successfully."
		 redirect_to  book_path(@book.id)
     else
      @books = Book.all
      flash[:notice] = ' errors prohibited this obj from being saved:'
      render "index"
     end
    end

    def show
    	@book = Book.find(params[:id])
    	@user = @book.user
    	@book_new = Book.new
    end

    def index
        @user = current_user
        @books = Book.all
        @book = Book.new
    end

    def edit
    	@book = Book.find(params[:id])
    end


    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
        flash[:notice] = "You have creatad book successfully."
        redirect_to  book_path(@book.id)

        else
        @books = Book.all
         flash[:notice]= ' errors prohibited this obj from being saved:'
        render "edit"
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

	private

    def book_params
        params.require(:book).permit(:title, :body)
    end

    def user_params
      params.require(:user).permit(:name,:profile_image,:introduction)
    end

    def  ensure_current_user
    @book = Book.find(params[:id])
     if @book.user_id != current_user.id
      redirect_to books_path
     end
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
   before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

	  def show
	      @book = Book.new
        @user = User.find(params[:id])
        @books = @user.books
    end

    def new
        @book = Book.new
        @user = User.new(user_params)
        if @user.save
         flash[:notice] = "successfully"
         redirect_to  user_path(current_user.id)
        else
         render "users/sign_up"
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def index
        @users = User.all
    	  @books = Book.all
    	  @book = Book.new
        @user = current_user
    end

    def update
        @user = User.find(params[:id])
          if  @user.update(user_params)
            flash[:notice] = "You have updated user successfully."
            redirect_to "/users/#{current_user.id}"
          else
            flash[:notice] = " errors prohibited this obj from being saved:"
            render :edit
          end
    end

  private


    def book_params
        params.require(:book).permit(:title, :body)
    end

    def user_params
        params.require(:user).permit(:name,:profile_image,:introduction)
    end

    def  ensure_current_user
    @user = User.find(params[:id])
     if @user.id != current_user.id
      redirect_to user_path(current_user.id)
     end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_image_helper.rb
module PostImageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
  <div class="container">
   <div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<%= form_for(@book, url: book_path(@book.id)) do |f| %>


    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>

    <%= f.text_area :body %>

  <nav>
     <%= f.submit 'Update Book', class: "btn btn-primary" %>
  </nav>
　<% end %>
<%= link_to "Show",book_path(@book.id)%>
<%= link_to "Back",books_path %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<% if @book.errors %>
   <ul>
<% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
       <% end %>
        </ul>
      <% end %>


<div class="container">
 <div class="row">

 <div class= "col-md-3">
   <h2>User info</h2>

   <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
   <h5>name</h5>
   <%= @user.name %>
   <h5>introduction</h5>
   <%= @user.introduction %><br/>
    <%= link_to edit_user_path(@user.id), class: "col-md-12 btn btn-primary" do %>
      <i class="fas fa-user-cog navbar-brand"></i>
    <% end %>


        <!-- form_for部分 -->
   <%= form_for(@book,  url: books_path) do |f| %>
    <h2>New book</h2>
    <h4>Title</h4>
    <%= f.text_field :title,class: "col-md-12" %>

    <h4>Opinion</h4>
     <%= f.text_field :body,class: "col-md-12" %>
    <nav>
    <%= f.submit 'Create Book',class: "container mt-3  col-md-12 btn btn-primary" %>
    </nav>
    <% end %>

  </div>





    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>

      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      </tr>





      <% @books.each do |book| %>
      <tr>
      <td><%= link_to user_path(book.user_id) do %>
      <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
      <% end %>

      <td><%=link_to book.title, book_path(book.id)%></td>
      <td><%=link_to book.body %></td>
      </tr>
      <% end %>
      </table>
    </div>

</div>
</div>

app/views/books/show.html.erb
   <% if @book.errors %>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
      </ul>
   <% end %>
<div class="container">
 <div class = "row">
 <div class= "col-md-3">
  <h2>User info</h2>
   <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>

   <h5>name</h5>
   <%= @book.user.name %>
   <h5>introduction</h5>
   <%= @book.user.introduction %><br/>
   <%= link_to edit_user_path(@user.id), class: "col-md-12 btn btn-primary" do %>
      <i class="fas fa-user-cog navbar-brand"></i>
   <% end %>

        <!-- form_for部分 -->
   <%= form_for(@book_new,  url: books_path)  do |f| %>


    <h2>New book</h2>
    <h4>Title</h4>
     <%= f.text_field :title,class: "col-md-12" %>
    <h4>Opinion</h4>
    <%= f.text_field :body,class: "col-md-12" %>
    <nav>
     <%= f.submit 'Create Book',class: "container mt-3  col-md-12 btn btn-primary" %>
    </nav>
    <% end %>
  </div>

  <div class= "col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class='table' >
    <tr>
    <td>
      <%= link_to user_path(@book.user_id) do %>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:'50x50',format: 'no_image.jpg' %>
         <nav>
           <%= @book.user.name %>
         </nav>
       <% end %>
    </td>



    <td><%= link_to @book.title %></td>
    <td><%= @book.body %></td>
    <% if @book.user_id == current_user.id %>
    <td><%= link_to"Edit", edit_book_path(@book.id),class:"btn-sm btn-success" %></td>
    <td><%= link_to "Destroy", book_path(@book.id), class:"btn-sm btn-danger destroy(@book.id)", method: :delete,data: {confirm: "削除しますか？"} %></td>
    <% end %>
    </tr>
    </table>
  </div>
 </div>
</div>

app/views/books/top.html.erb
<h1>top</h1>
<div class="container">
  
  <table class="table table-striped">
  </table>
  
  
  
  

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        welcome to
        <i class="fas fa-book">
        </i>
        <strong>Bookers</strong>
        !
      </h1>
    </div>
  </div>
  </mian>

app/views/homes/top.html.erb
<div class='container'>
 <div class="row">
   <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to
 <i class="fas fa-book"></i>
  <span class='glyphicon glyphicon-book'></span>
    Bookers !!
</h1>

<p>In<span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about varioius books!</p>


  <div class=" btn-wrapper">
      <div class="row">
      </div>
   <div class="btn-wrapper">
      <div class="row">
        <div class="mx-auto">
      <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
      </div>
      </div>
      <div class="row">
        <div class="mx-auto">
      <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
     </div>
     </div>
   </div>
 </div>
 </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href="/">
         <span>Bookers</span>
       </a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user), class:'navbar-brand' do %>
           <i class="fas fa-home">Home</i>
          <% end  %>
        </li>
        <li>
          <%= link_to users_path,class:"navbar-brand" do %>
           <i class="fas fa-users navbar-brand">Users</i>
          <% end  %>
        </li>
        <li>

          <%= link_to books_path, class:'navbar-brand' do %>
           <i class="fas fa-book-open navbar-brand">Books</i>
          <% end  %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: 'navbar-brand' do  %>
           <i class="fas fa-sign-out-alt navbar-brand">logout</i>
          <% end  %>
        </li>



       <% else %>
        <li>
          <%= link_to "/", class:'navbar-brand' do %>
           <i class="fas fa-home navbar-brand">Home</i>
          <% end  %>
        </li>
        <li>
          <%= link_to "/home/about", class:'navbar-brand' do %>
           <i class="fas fa-link navbar-brand">About</i>
          <% end  %>
        </li>
        <li>
          <%= link_to "/users/sign_up", class:'navbar-brand' do %>
           <i class="fas fa-user-plus navbar-brand">sign up</i>
          <% end  %>
        </li>
        <li>
          <%= link_to "/users/sign_in", class:'navbar-brand' do %>
           <i class="fas fa-sign-in-alt navbar-brand">login</i>
          <% end  %>
        </li>
       <% end %>
       </div>
      </div>
    </header>

  <% if flash[:notice] %>
    <div class="flash">
         <%= flash[:notice] %>
    </div>
<% end %>



    <%= yield %>
  </body>
  <footer>
    <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
    </div>
  </footer>
</html>

app/views/post_image/index.html.erb
<% @books.each do |post_image| %>
<div>
  <%= attachment_image_tag post_image, :image %>
  <p>投稿ユーザー画像：<%= image_tag('sample-author1.jpg') %></p>
  <p>ショップ名：<%= post_image.shop_name %></p>
  <p>説明：<%= post_image.caption %></p>
  <p>ユーザーネーム：<%= post_image.user.name %></p>
</div>
<% end %>
<%= paginate @books %>

app/views/users/edit.html.erb
 <% if @user.errors %>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>

<div class="box">
<h2>User   info</h2>

<%= form_for(@user, url: user_path(current_user.id)) do |f| %>
    <h4>Name</h4>
    <%= f.text_field :name %>
    <h4>Image</h4>
  <%= f.attachment_field :profile_image %>
    <h4>introduction</h4>
      <%= f.text_area :introduction %>
    <%= f.submit 'Update User' %>
<% end %>

</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">


<div class= "col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
 <div>
  <h5>name</h5>
  <%= @user.name %>
  <h5>introduction</h5>
  <%= @user.introduction %><br/>
  <%= link_to edit_user_path(@user.id), class: "col-md-12 btn btn-primary" do %>
      <i class="fas fa-user-cog navbar-brand"></i>
  <% end %>


       <!-- form_for部分 -->
  <%= form_for(@book,  url: books_path) do |f| %>


        <h2>New book</h2>
        <h4>Title</h4>
        <%= f.text_field :title,class: "col-md-12" %>

        <h4>Opinion</h4>
        <%= f.text_field :body,class: "col-md-12" %>
        <nav>

        <%= f.submit 'Create Book',class: "container mt-3  col-md-12 btn btn-primary" %>
        </nav>
        <% end %>
  </div>
</div>


  <div class= "col-md-8 offset-md-1">
    <h2>Users</h2>
   <table class='table table-hover table-inverse'>
      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      </tr>
    <% @users.each do |user| %>
    <tr>
    <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
   <th><%= user.name %><th>
   <th><%= link_to"Show",user_path(user.id) %></th>
   </tr>
   <% end %>
   </table>
  </div>

  </div>
  </div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">

  <div class= "col-md-3">
    <h2>User info</h2>


    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
    <h5>name</h5>
    <%= @user.name %>
    <h5>introduction</h5>
    <%= @user.introduction %>
    <%= link_to edit_user_path(@user.id), class: "col-md-12 btn btn-primary" do %>
      <i class="fas fa-user-cog navbar-brand"></i>
    <% end %>

    <%= form_for(@book,  url: books_path) do |f| %>
    <h2>New book</h2>
    <h4>Title</h4>
    <%= f.text_field :title,class: "col-md-12" %>
    <h4>Opinipn</h4>
    <%= f.text_field :body,class: "col-md-12" %>
    <nav>
        <%= f.submit 'Create Book',class: "container mt-3  col-md-12 btn btn-primary" %>
    </nav>
    <% end %>

  </div>




  <div class= "col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class='table table-hover table-inverse'>

   <tr>
     <th></th>
   <th>Title</th>
   <th>Opinion</th>
   <th colspan="3"></th>
   </tr>

   <% @books.each do |book| %>
    <%= link_to user_path(@user.id) do %>
   <tr>
   <td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
   <% end %>
   <td><%=link_to book.title, book_path(book.id)%></td>
   <td><%= book.body %></td>
   </tr>
   <% end %>
   </table>

  </div>
</div>
</div>